boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'

urlpatterns = [
    path("", views.index, name='index'),
    path("write/", views.write, name='write'),
    path("write/success/", views.write_success, name='write_success'),
    path("<int:post_id>/", views.detail, name='detail'),
    path("<int:post_id>/edit/", views.edit, name="edit"),
    path("<int:post_id>/delete/", views.delete, name="delete"),
]

myboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("boards/", include('boards.urls')),
]

boards/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.CharField(max_length=50)
    created_at = models.DateTimeField('created date', auto_now_add=True)
    like = models.IntegerField(default=0)
    num_comments = models.IntegerField(default=0)

    def __str__(self):
        return self.title + " - " + self.author


class Comment(models.Model):
    author = models.CharField(max_length=50)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField('created date', auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.content + " - " + self.author

boards/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment


def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    context = {'post_list': post_list}
    return render(request, 'boards/index.html', context)


def write(request):
    return render(request, 'boards/write.html')


def write_success(request):
    author = request.POST['author']
    title = request.POST['title']
    content = request.POST['content']
    saved_post = Post(author=author, title=title, content=content)
    saved_post.save()
    return redirect('boards:index')


def detail(request, post_id):
    try:
        json_object = json.loads(request.body)
        author = json_object.get('comment-author')
        content = json_object.get('comment-content')
        comment = Comment(author=author, content=content, post_id=post_id)
        comment.save()
        post = get_object_or_404(Post, pk=post_id)
        post.num_comments += 1
        post.save()
    except:
        print('No comment posted')
    try:
        json_object = json.loads(request.body)
        like = json_object.get('like')
        post = get_object_or_404(Post, pk=post_id)
        if like == 1:
            post.like += 1
            post.save()
    except:
        print('broken like button')

    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'boards/detail.html', context)


def edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        context = {'post': post}
        author = request.POST['author']
        title = request.POST['title']
        content = request.POST['content']
        post.author = author
        post.title = title
        post.content = content
        post.save()
        return redirect('boards:index')
    except:
        print('수정 실패')
    return render(request, 'boards/edit.html', context)


def delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('boards:index')

boards/templates/boards/detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <style>
        th,
        td {
            background-clip: padding-box;
            scroll-snap-align: start;
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        <h4>글 번호: {{ post.id }}</h4>
        <h4>작성자: {{ post.author }}</h4>
        <h4>제목: {{ post.title }}</h4>
        <h4>내용:</h4>
        <p>{{ post.content }}</p>
        <h4>좋아요: {{ post.like }}</h4>
        <br><br>

        <input type="button" value="수정" onclick="location.href='{% url 'boards:edit' post.id %}'">
        <input type="button" value="삭제" onclick="location.href='{% url 'boards:delete' post.id %}'">
        <input type="button" id="btn-like" value="좋아요">
        <input type="button" value="목록으로" onclick="location.href='{% url 'boards:index'%}'">
        <br><br>
    </div>
    <div>
        <h3>댓글</h3>
        <table style="border-collapse: collapse; border-spacing: 0; width: 90%;">
            <th style="width: 20%">작성자</th>
            <th style="width: 80%">내용</th>
            {% if post.comment_set %}
            {% for comment in post.comment_set.all %}
                <tr>
                    <td>{{ comment.author }}</td>
                    <td>{{ comment.content }}</td>
                </tr>
            {% endfor %}
            {% endif %}
                <tr>
                    <td><input type="text" id="comment-author"></td>
                    <td><input type="text" id="comment-content" style="width: 400px"></td>
                </tr>

        </table>
        <br>
        <input type="button" id="btn-comment" value="댓글 추가">
    </div>
</body>
<script>
    let btn_comment = document.querySelector('#btn-comment');
    let btn_like = document.querySelector('#btn-like');

    btn_comment.addEventListener('click', e => {
        let author = document.querySelector('#comment-author').value;
        let content = document.querySelector('#comment-content').value;

        let param = {
            'comment-author': author,
            'comment-content': content,
        }

        $.ajax({
            url: "{% url 'boards:detail' post.id %}",
            type: 'POST',
            headers: {
                'X-CSRFTOKEN': '{{ csrf_token }}'
            },
            data: JSON.stringify(param),
            success: function(data) {
                document.location.reload()
            },
            error: function() {
                alert('댓글 등록 실패');
            }
        })
    })

    btn_like.addEventListener('click', e => {
        $.ajax({
            url: "{% url 'boards:detail' post.id %}",
            type: 'POST',
            headers: {
                'X-CSRFTOKEN': '{{ csrf_token }}'
            },
            data: JSON.stringify({'like':1}),
            success: function(data) {
                document.location.reload()
            },
            error: function() {
                alert('좋아요 안됨 ㅠㅠ');
            }
        })
    })



</script>
</html>

boards/templates/boards/edit.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
</head>
<body>
    <div>
        <form method="post" action="{% url "boards:edit" post.id %}">
            {% csrf_token %}
            <h1>글 수정하기</h1>
            <h4>작성자: <input type="text" value="{{ post.author }}" name="author" required></h4>
            <h4>제목: <input type="text" value="{{ post.title }}" name="title" required></h4>
            <h4>내용: </h4>
            <textarea rows="20" cols="60" name="content" required>{{ post.content }}</textarea>
            <br><br>
            <input type="submit" value="저장">
            <input type="button" value="취소" onclick="location.href='{% url 'boards:index' %}'">
        </form>
    </div>
</body>
</html>

boards/templates/boards/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
    <style>
        th,
        td {
            border: 1px solid #aaa;
            background-clip: padding-box;
            scroll-snap-align: start;
            text-align: center;
        }
    </style>
</head>
<body>
    <input type="button" value="글쓰기" onclick="location.href='{% url 'boards:write' %}'">
    <br>
    {% if post_list %}
        <table style="border: darkgray 1px solid; border-collapse: separate; border-spacing: 0; width: 90%; margin: 20px 0;">
        <th style="width: 7%">번호</th>
        <th style="width: auto">글 제목</th>
        <th style="width: 15%">작성자</th>
        <th style="width: 19%">작성일</th>
        <th style="width: 7%">좋아요</th>
        <th style="width: 7%">댓글수</th>
        {% for post in post_list %}
            <tr>
                <td>{{ post.id }}</td>
                <td><a href="{% url 'boards:detail' post.id %}">{{ post.title }}</a></td>
                <td>{{ post.author }}</td>
                <td>{{ post.created_at.date }}</td>
                <td>{{ post.like }}</td>
                <td>{{ post.num_comments }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h1>아직 글이 없습니다.</h1>
    {% endif %}
</body>
</html>

boards/templates/boards/write.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
</head>
<body>
    <div>
        <form method="post" action="{% url 'boards:write_success' %}">
            {% csrf_token %}
            <h1>새 글 쓰기</h1>
            <h4>작성자: <input type="text" name="author" required></h4>
            <h4>제목: <input type="text" name="title" required></h4>
            <h4>내용: </h4>
            <textarea rows="20" cols="60" name="content" required></textarea>
            <br><br>
            <input type="submit" value="저장">
            <input type="button" value="취소" onclick="location.href='{% url 'boards:index' %}'">
        </form>
    </div>
</body>
</html>